// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`shows the correct errors in stderr when failing tests 1`] = `
"FAIL __tests__/failure.test.js
  ✕ fail with expected non promise values
  ✕ fail with expected non promise values and not
  ✕ fail with expected promise values
  ✕ fail with expected promise values and not

  ● fail with expected non promise values

    Error
      Error: Expected value to have length:
        2
      Received:
        1
      received.length:
        1

  ● fail with expected non promise values and not

    Error
      Error: Expected value to not have length:
        2
      Received:
        1,2
      received.length:
        2

  ● fail with expected promise values

    Expected value to have length:
      2
    Received:
      1
    received.length:
      1

      22 | 
      23 | it('fail with expected promise values', async () => {
    > 24 |   await (expect(Promise.resolve([1])): any).resolves.toHaveLengthAsync(
         |                                                      ^
      25 |     Promise.resolve(2)
      26 |   );
      27 | });
      
      at __tests__/failure.test.js:24:54
      at __tests__/failure.test.js:11:191
      at __tests__/failure.test.js:11:437
      at __tests__/failure.test.js:11:99

  ● fail with expected promise values and not

    Expected value to not have length:
      2
    Received:
      1,2
    received.length:
      2

      28 | 
      29 | it('fail with expected promise values and not', async () => {
    > 30 |   await (expect(Promise.resolve([1, 2])).resolves.not: any).toHaveLengthAsync(
         |                                                             ^
      31 |     Promise.resolve(2)
      32 |   );
      33 | });
      
      at __tests__/failure.test.js:30:61
      at __tests__/failure.test.js:11:191
      at __tests__/failure.test.js:11:437
      at __tests__/failure.test.js:11:99

"
`;
